### ISSUE TITLE
EventRecorder always post PodVerified

### ISSUE THREAD

**Issue by eumel8** [eumel8/cosignwebhook#30]
version: 4.0.2

Just realized that the EventRecorder always puts a message in the event channel if a Pod is create, also if there is no signature and no verification key is present.

```
60m         Normal    PodVerified         pod/demoapp-bcb9687f9-wdc2h     Signature of pod's images(s) verified successfully
```

I think this comes from the [end ](https://github.com/eumel8/cosignwebhook/blob/main/webhook/cosignwebhook.go#L244)of Admission verification process. 

accept is the right return after finishing validation process, but there is still the option that we never verified an image

cc @puffitos

**Comment by puffitos** [comment]
Correct, this happens because we don't differentiate the "I don't have to do any validation" event. If no validation needs to happen, we return the _relatively_ generic "Signature of pod's images(s) verified successfully".

We can go 2 ways here:

- Return a truly generic message like "Verification passed"
- Actually separate the 2 events and emit a different (success) msg when we don't have to verify anything.

Let's do the second one, yeah? ;)
